spring:
  application:
    name: graphql-project
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
